steps:
  # Install dependencies and build the app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Deploy the app to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Fetch secret and store it as a file
        gcloud secrets versions access 1 --secret="IMAGE-PROCESSING-SERVER" > /app/image-processing-server-credentials.json

        # Deploy the app
        gcloud run deploy gcr-upload-svg-next --image gcr.io/image-processing-server-435318/upload-svg-next --region us-central1 --platform managed --allow-unauthenticated

images:
  - gcr.io/image-processing-server-435318/upload-svg-next
