services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      NEXT_PUBLIC_MONGODB_URI: mongodb+srv://pasanmahee:fVgPys0uknMCuT8S@cluster0.zwasfmo.mongodb.net/svgfacetpaintbynumber?retryWrites=true&w=majority
